import { FocusEventList, type FocusEvent } from '@/components/examinations/focus-events';
import { Head, useForm } from '@inertiajs/react';
import { Button, ButtonLink } from '@/components/ui/button';
import { PageHeader } from '@/components/ui/page-header';
import { Pagination } from '@/components/ui/pagination';
import type { Paginated } from '@/types';
interface Essay { id: number; prompt: string; answer: string; maxPoints: string; grade: string | null; comment: string | null; version: number; grader: string | null; gradedAt: string | null }
interface Revision { id: number; itemId: number; actor: string; at: string; before: string | null; after: string; reason: string | null; commentBefore: string | null; commentAfter: string | null }
export default function GradeAttempt({ examination, attempt, questions, history, nextAttemptId, focusEvents }: { examination: { id: number; title: string }; attempt: { id: number; number: number; candidate: string; candidateNumber: string; status: string; percentage: string | null }; questions: Essay[]; history: Paginated<Revision>; nextAttemptId: number | null; focusEvents: FocusEvent[] }) {
    return <><Head title={`Grade attempt · ${attempt.candidate}`} /><PageHeader title={`Attempt ${attempt.number}`} description={`${attempt.candidate} · ${attempt.candidateNumber} · ${examination.title}`} actions={<><ButtonLink href={`/examinations/${examination.id}/grading`}>Back to queue</ButtonLink>{nextAttemptId && <ButtonLink href={`/examination-attempts/${nextAttemptId}/grading`}>Next pending</ButtonLink>}</>} /><div className="mb-6 rounded-xl border border-line bg-surface p-5"><p className="text-sm text-ink-muted">Current result</p><p className="mt-1 text-xl font-semibold">{attempt.status === 'pending_review' ? 'Pending essay review' : `Final · ${attempt.percentage ?? '—'}%`}</p></div><div className="space-y-6">{questions.map((question) => <EssayForm key={`${attempt.id}-${question.id}-${question.version}`} attemptId={attempt.id} question={question}  />)}</div><section className="mt-8" aria-labelledby="grading-history"><h2 id="grading-history" className="text-lg font-semibold">Grading history</h2><div className="mt-3 overflow-x-auto rounded-xl border border-line bg-surface"><table className="w-full min-w-[42rem] text-left text-sm"><thead className="border-b border-line bg-surface-muted"><tr><th className="p-3">Time</th><th className="p-3">Item</th><th className="p-3">Change</th><th className="p-3">Reason</th></tr></thead><tbody>{history.data.map((revision) => <tr key={revision.id} className="border-b border-line last:border-0"><td className="p-3">{new Date(revision.at).toLocaleString()}<br /><span className="text-ink-muted">{revision.actor}</span></td><td className="p-3">Question {revision.itemId}</td><td className="p-3">{revision.before ?? '—'} → {revision.after}{revision.commentBefore !== revision.commentAfter && <details className="mt-2"><summary className="cursor-pointer">Feedback change</summary><p className="mt-2 whitespace-pre-wrap">Previous: {revision.commentBefore || 'None'}</p><p className="mt-2 whitespace-pre-wrap">New: {revision.commentAfter || 'None'}</p></details>}</td><td className="p-3">{revision.reason ?? 'Initial score'}</td></tr>)}</tbody></table>{history.data.length === 0 && <p className="p-5 text-ink-muted">No scores have been saved.</p>}<Pagination page={history} noun={{ one: 'revision', other: 'revisions' }} /></div></section><FocusEventList events={focusEvents} /></>;
}
function EssayForm({ attemptId, question }: { attemptId: number; question: Essay }) {
    const form = useForm({ item_id: question.id, score: question.grade ?? '', version: question.version, comment: question.comment ?? '', reason: '', next: false });
    const correction = question.grade !== null;
    return <form onSubmit={(event) => { event.preventDefault(); form.put(`/examination-attempts/${attemptId}/essay-grade`, { preserveScroll: true }); }} className="rounded-xl border border-line bg-surface p-5"><p className="font-medium">{question.prompt}</p><p className="mt-3 whitespace-pre-wrap rounded-lg bg-surface-muted p-4 text-sm">{question.answer || 'No answer submitted.'}</p><div className="mt-4 grid gap-4 sm:grid-cols-[10rem_1fr]"><label className="text-sm font-medium">Score / {question.maxPoints}<input type="number" min="0" max={question.maxPoints} step="0.01" className="mt-2 block min-h-11 w-full rounded-md border border-line-strong p-3" value={form.data.score} onChange={(event) => form.setData('score', event.target.value)} required /></label><label className="text-sm font-medium">Instructor comment<textarea className="mt-2 block min-h-24 w-full rounded-md border border-line-strong p-3" value={form.data.comment} onChange={(event) => form.setData('comment', event.target.value)} /></label></div>{correction && <label className="mt-4 block text-sm font-medium">Reason for correction<textarea className="mt-2 block min-h-20 w-full rounded-md border border-line-strong p-3" value={form.data.reason} onChange={(event) => form.setData('reason', event.target.value)} required /></label>}<div className="mt-4 flex flex-wrap items-center gap-3">{<><Button type="submit" loading={form.processing}>Save score</Button><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.data.next} onChange={(event) => form.setData('next', event.target.checked)} />Open next pending attempt</label></>}{question.gradedAt && <span className="text-sm text-ink-muted">Saved by {question.grader} on {new Date(question.gradedAt).toLocaleString()}</span>}</div>{Object.values(form.errors).map((error) => <p key={error} role="alert" className="mt-2 text-danger-fg">{error}</p>)}</form>;
}


