import { Head, Link } from '@inertiajs/react';
import { ButtonLink } from '@/components/ui/button';
import { PageHeader } from '@/components/ui/page-header';
import { Pagination } from '@/components/ui/pagination';
import type { Paginated } from '@/types';
interface Attempt { id: number; number: number; candidate: string; candidateNumber: string; submittedAt: string | null; status: string; percentage: string | null }
export default function ExaminationGrading({ examination, attempts, status = 'pending' }: { examination: { id: number; title: string }; attempts: Paginated<Attempt>; status?: string }) {
    return <><Head title={`Essay grading · ${examination.title}`} /><PageHeader title="Essay grading" description={`${examination.title} · review subjective responses and record scores.`} actions={<ButtonLink href={`/examinations/${examination.id}`}>Back to examination</ButtonLink>} /><div className="mb-4 flex flex-wrap gap-2" role="tablist" aria-label="Grading status"><Link href={`/examinations/${examination.id}/grading?status=pending`} className={'rounded-md px-3 py-2 text-sm ' + (status === 'pending' ? 'bg-primary-700 text-white' : 'border border-line bg-surface')}>Pending review</Link><Link href={`/examinations/${examination.id}/grading?status=graded`} className={'rounded-md px-3 py-2 text-sm ' + (status === 'graded' ? 'bg-primary-700 text-white' : 'border border-line bg-surface')}>Completed</Link></div><div className="overflow-x-auto rounded-xl border border-line bg-surface"><table className="w-full min-w-[42rem] text-left text-sm"><caption className="sr-only">Examination submissions</caption><thead className="border-b border-line bg-surface-muted"><tr><th className="p-4 font-semibold">Candidate</th><th className="p-4 font-semibold">Submitted</th><th className="p-4 font-semibold">Status</th><th className="p-4 font-semibold">Action</th></tr></thead><tbody>{attempts.data.map((attempt) => <tr key={attempt.id} className="border-b border-line last:border-0"><td className="p-4"><p className="font-medium">{attempt.candidate}</p><p className="text-ink-muted">{attempt.candidateNumber} · Attempt {attempt.number}</p></td><td className="p-4">{attempt.submittedAt ? new Date(attempt.submittedAt).toLocaleString() : '—'}</td><td className="p-4">{attempt.status === 'pending_review' ? 'Pending review' : `Graded${attempt.percentage ? ` · ${attempt.percentage}%` : ''}`}</td><td className="p-4"><ButtonLink href={`/examination-attempts/${attempt.id}/grading`} size="sm">Open response</ButtonLink></td></tr>)}</tbody></table>{attempts.data.length === 0 && <p className="p-6 text-ink-muted">No submissions match this filter.</p>}<Pagination page={attempts} noun={{ one: 'submission', other: 'submissions' }} /></div></>;
}
