import { Head, Link } from '@inertiajs/react';
import { ButtonLink } from '@/components/ui/button';
import { PageHeader } from '@/components/ui/page-header';
import { Pagination } from '@/components/ui/pagination';
import type { Paginated } from '@/types';
interface Exam { id: number; title: string; kind: string; lifecycle: { label: string }; class_subject: { subject: { name: string }; class_batch: { name: string } }; duration_minutes: number | null }
export default function ExaminationIndex({ examinations }: { examinations: Paginated<Exam> }) {
    return <><Head title="Examinations" /><PageHeader title="Quizzes & Examinations" description="Build, review, and monitor assessments for your assigned subjects." actions={<ButtonLink href="/examinations/create">Create assessment</ButtonLink>} /><section className="rounded-xl border border-line bg-surface"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-line"><tr>{['Title', 'Class / subject', 'Time limit', 'Status'].map((label) => <th key={label} className="p-4">{label}</th>)}</tr></thead><tbody>{examinations.data.map((exam) => <tr key={exam.id} className="border-b border-line"><td className="p-4"><Link className="font-medium text-primary-700 underline" href={`/examinations/${exam.id}`}>{exam.title}</Link><p className="capitalize text-ink-muted">{exam.kind}</p></td><td className="p-4">{exam.class_subject.class_batch.name} · {exam.class_subject.subject.name}</td><td className="p-4">{exam.duration_minutes ? `${exam.duration_minutes} min` : 'Not set'}</td><td className="p-4">{exam.lifecycle.label}</td></tr>)}</tbody></table>{examinations.total === 0 && <p className="p-8 text-center text-ink-muted">No examinations yet. Create a draft for an assigned subject to begin.</p>}</div><Pagination page={examinations} noun={{ one: 'assessment', other: 'assessments' }} /></section></>;
}
