import { QuestionMediaList } from '@/components/question-bank/question-media';
import { FocusSummaryCell, type FocusSummary } from '@/components/examinations/focus-events';
import { Head, router, useForm } from '@inertiajs/react';
import { useEffect, useState } from 'react';
import { Button, ButtonLink } from '@/components/ui/button';
import { ConfirmDialog } from '@/components/ui/confirm-dialog';
import { FormField, TextInput } from '@/components/ui/form-field';
import { PageHeader } from '@/components/ui/page-header';
import type { StaffQuestion } from '@/types/question-bank';
interface Examination { can_post_grades: boolean; posted_assessment_id: number | null; id: number; title: string; description: string | null; status: string; lifecycle: { label: string }; duration_minutes: number | null; attempt_limit: number; passing_score: string | null; release_results: boolean; opens_at: string | null; closes_at: string | null; randomize_questions: boolean; randomize_choices: boolean; allow_back_navigation: boolean; one_question_at_a_time: boolean; auto_submit: boolean; has_access_code: boolean; examination_questions: { id: number; points: string; question: StaffQuestion }[] }
interface MonitoringRow { candidate: { id: number; number: string; name: string }; status: string; attemptNumber: number | null; answered: number; questionCount: number; lastActivityAt: string | null; focus: FocusSummary | null }
interface Monitoring { refreshedAt: string; totals: { candidates: number; active: number; inactive: number; submitted: number; expired: number; notStarted: number; leftScreen: number }; candidates: MonitoringRow[] }
export default function ExaminationShow({ examination: exam, monitoring }: { examination: Examination; monitoring: Monitoring }) {
    const [confirm, setConfirm] = useState<'publish' | 'archive' | null>(null);
    const [monitorPage, setMonitorPage] = useState(1);
    const publication = useForm({ confirmation: true });
    const archive = useForm({ reason: '' });
    const release = useForm({ release_results: exam.release_results, reason: '' });
    useEffect(() => { if (exam.status !== 'published') return; const timer = window.setInterval(() => router.reload({ only: ['monitoring'] }), 15000); return () => window.clearInterval(timer); }, [exam.status]);
    const draft = exam.status === 'draft';
    const pages = Math.max(1, Math.ceil(monitoring.candidates.length / 25));
    const page = Math.min(monitorPage, pages);
    const rows = monitoring.candidates.slice((page - 1) * 25, page * 25);
    return <><Head title={exam.title} /><PageHeader title={exam.title} description="Review delivery settings and questions before publishing." actions={<><ButtonLink href="/examinations" variant="secondary">All examinations</ButtonLink>{draft && <><ButtonLink href={`/examinations/${exam.id}/edit`} variant="secondary">Edit settings</ButtonLink><ButtonLink href={`/examinations/${exam.id}/questions`}>Manage questions</ButtonLink></>}<ButtonLink href={`/examinations/${exam.id}/grading`} variant="secondary">Essay grading</ButtonLink>{!draft && exam.can_post_grades && <ButtonLink href={`/examinations/${exam.id}/gradebook`}>{exam.posted_assessment_id ? "View posted grades" : "Post to gradebook"}</ButtonLink>}</>} />
        <div className="grid gap-4 sm:grid-cols-4"><Summary label="Status" value={exam.lifecycle.label} /><Summary label="Time limit" value={exam.duration_minutes ? `${exam.duration_minutes} minutes` : 'Not set'} /><Summary label="Attempts" value={String(exam.attempt_limit)} /><Summary label="Passing score" value={exam.passing_score !== null ? `${exam.passing_score}%` : 'Not configured'} /></div>
        {exam.posted_assessment_id && <section className="mt-6 rounded-xl border border-line bg-surface p-5"><h2 className="font-semibold">Grades posted to the gradebook</h2><p className="mt-2 text-sm text-ink-muted">Posted grades are retained even if examination results are hidden later. Regrading an examination does not change the posted assessment; record any gradebook correction separately with a reason.</p></section>}
        <section className="mt-6 rounded-xl border border-line bg-surface p-5"><h2 className="text-lg font-semibold">Delivery review</h2><p className="mt-2 whitespace-pre-wrap">{exam.description || 'No additional instructions.'}</p><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><Detail label="Opens" value={exam.opens_at ? new Date(exam.opens_at).toLocaleString() : 'Immediately after publication'} /><Detail label="Closes" value={exam.closes_at ? new Date(exam.closes_at).toLocaleString() : 'No closing schedule'} /><Detail label="Question order" value={exam.randomize_questions ? 'Randomized per attempt' : 'As listed below'} /><Detail label="Choices" value={exam.randomize_choices ? 'Randomized' : 'Original order'} /><Detail label="Navigation" value={exam.allow_back_navigation ? 'Can revisit questions' : 'Forward only'} /><Detail label="Question display" value={exam.one_question_at_a_time ? 'One at a time' : 'Question navigation available'} /><Detail label="Time expiry" value={exam.auto_submit ? 'Submit saved answers automatically' : 'Mark attempt expired'} /><Detail label="Access code" value={exam.has_access_code ? 'Required to start' : 'Not required'} /></dl></section>
        <section className="mt-6 rounded-xl border border-line bg-surface p-5"><h2 className="text-lg font-semibold">Question review · {exam.examination_questions.length} items · {exam.examination_questions.reduce((sum, item) => sum + Number(item.points), 0).toFixed(2)} points</h2><p className="mt-1 text-sm text-ink-muted">Correct answers below are visible only to authorized instructors.</p><ol className="mt-4 space-y-4">{exam.examination_questions.map((item, index) => <li key={item.id} className="rounded-lg border border-line p-4"><p className="text-sm text-ink-muted">Question {index + 1} · {item.question.type.label} · {item.points} points</p><p className="my-2 whitespace-pre-wrap font-medium">{item.question.prompt}</p><QuestionMediaList className="my-3 space-y-3" media={item.question.media} urlFor={(media) => media.url} /><ul className="space-y-1">{item.question.choices.map((choice) => <li key={choice.id} className={choice.isCorrect ? 'font-medium text-success-fg' : ''}>{choice.label}. {choice.text}{choice.isCorrect && ' — Correct answer'}</li>)}</ul></li>)}</ol>{exam.examination_questions.length === 0 && <p className="mt-4 text-ink-muted">Add questions from the Question Bank before publishing.</p>}{draft && <div className="mt-5"><Button disabled={!exam.duration_minutes || exam.examination_questions.length === 0} onClick={() => setConfirm('publish')}>Publish examination</Button></div>}{Object.values(publication.errors).map((error, i) => <p key={i} role="alert" className="mt-2 text-danger-fg">{error}</p>)}</section>
        {!draft && <section className="mt-6 rounded-xl border border-line bg-surface p-5"><h2 className="text-lg font-semibold">Examination participation</h2><p className="mt-1 text-sm text-ink-muted">Refreshes every 15 seconds while published · updated {new Date(monitoring.refreshedAt).toLocaleTimeString()}. Inactive means no recent server contact; it does not confirm disconnection. Left screen counts candidates who switched tabs or apps or focused another window during the attempt; it is an indicator to follow up on, not proof.</p><div className="mt-4 grid gap-3 sm:grid-cols-4 lg:grid-cols-7">{Object.entries(monitoring.totals).map(([label, count]) => <Summary key={label} label={label === 'notStarted' ? 'Not started' : label === 'leftScreen' ? 'Left screen' : label} value={String(count)} />)}</div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[46rem] text-left text-sm"><caption className="sr-only">Candidate statuses</caption><thead className="border-b border-line"><tr>{['Candidate', 'Status', 'Progress', 'Left screen', 'Last activity'].map((label) => <th key={label} className="p-3">{label}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.candidate.id} className="border-b border-line"><td className="p-3"><p className="font-medium">{row.candidate.name}</p><p className="text-ink-muted">{row.candidate.number}</p></td><td className="p-3 capitalize">{row.status.replace('_', ' ')}</td><td className="p-3">{row.answered} / {row.questionCount}</td><td className="p-3"><FocusSummaryCell summary={row.focus} /></td><td className="p-3">{row.lastActivityAt ? new Date(row.lastActivityAt).toLocaleTimeString() : '—'}</td></tr>)}</tbody></table></div><div className="mt-4 flex items-center justify-between"><Button variant="secondary" size="sm" disabled={page <= 1} onClick={() => setMonitorPage(page - 1)}>Previous</Button><span className="text-sm">Page {page} of {pages}</span><Button variant="secondary" size="sm" disabled={page >= pages} onClick={() => setMonitorPage(page + 1)}>Next</Button></div></section>}
        <form className="mt-6 space-y-4 rounded-xl border border-line bg-surface p-5" onSubmit={(e) => { e.preventDefault(); release.put(`/examinations/${exam.id}/results`, { preserveScroll: true }); }}><h2 className="text-lg font-semibold">Candidate results</h2><label className="flex min-h-11 items-center gap-3"><input className="size-5" type="checkbox" checked={release.data.release_results} onChange={(e) => release.setData('release_results', e.target.checked)} />Release results to candidates</label><FormField label="Reason for visibility change" required error={release.errors.reason}><TextInput value={release.data.reason} onChange={(e) => release.setData('reason', e.target.value)} maxLength={500} /></FormField><Button type="submit" variant="secondary" loading={release.processing}>Save result visibility</Button></form>
        {exam.status !== 'archived' && <form className="mt-6 space-y-4 rounded-xl border border-line bg-surface p-5" onSubmit={(e) => { e.preventDefault(); setConfirm('archive'); }}><h2 className="text-lg font-semibold">Archive examination</h2><p className="text-sm text-ink-muted">Removes this examination from candidate availability and keeps its historical records. All attempts must be finished.</p><FormField label="Reason for archiving" required error={archive.errors.reason}><TextInput maxLength={500} value={archive.data.reason} onChange={(e) => archive.setData('reason', e.target.value)} /></FormField><Button type="submit" variant="secondary">Archive</Button>{Object.values(archive.errors).map((error, i) => <p key={i} role="alert" className="text-danger-fg">{error}</p>)}</form>}
        <ConfirmDialog open={confirm === 'publish'} title="Publish examination?" description="Eligible candidates will be able to start during the availability window. Questions and delivery settings will be locked." confirmLabel="Publish" tone="primary" processing={publication.processing} onCancel={() => setConfirm(null)} onConfirm={() => publication.post(`/examinations/${exam.id}/publish`, { onFinish: () => setConfirm(null) })} />
        <ConfirmDialog open={confirm === 'archive'} title="Archive examination?" description="Candidates will no longer be able to start this examination. Existing results and history will be retained." confirmLabel="Archive" processing={archive.processing} onCancel={() => setConfirm(null)} onConfirm={() => archive.post(`/examinations/${exam.id}/archive`, { onFinish: () => setConfirm(null) })} />
    </>;
}
function Summary({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-line bg-surface p-4"><p className="text-sm capitalize text-ink-muted">{label}</p><p className="mt-1 font-semibold">{value}</p></div>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><dt className="text-ink-muted">{label}</dt><dd className="font-medium">{value}</dd></div>; }
