import { Head, router } from '@inertiajs/react';
import { useEffect } from 'react';
import { ButtonLink } from '@/components/ui/button';
import { PageHeader } from '@/components/ui/page-header';

interface Examination { id: number; title: string; status: string; duration_minutes: number | null; attempt_limit: number; passing_score: string | null; release_results: boolean; examination_questions?: Array<{ id: number; points: string; question?: { prompt: string } }> }
interface MonitoringRow { candidate: { id: number; number: string; name: string }; status: string; attemptNumber: number | null; answered: number; questionCount: number; lastActivityAt: string | null }
interface Monitoring { refreshedAt: string; totals: { candidates: number; active: number; inactive: number; submitted: number; expired: number; notStarted: number }; candidates: MonitoringRow[] }

export default function ExaminationShow({ examination, monitoring }: { examination: Examination; monitoring: Monitoring }) {
    useEffect(() => {
        const timer = window.setInterval(() => router.reload({ only: ['monitoring'] }), 15000);
        return () => window.clearInterval(timer);
    }, []);
    return <><Head title={examination.title} /><PageHeader title={examination.title} description="Review questions, monitor grading, and publish when ready." actions={<><ButtonLink href={`/examinations/${examination.id}/questions`}>Manage questions</ButtonLink><ButtonLink href={`/examinations/${examination.id}/grading`}>Essay grading</ButtonLink></>} /><div className="grid gap-4 sm:grid-cols-4"><Summary label="Status" value={examination.status} /><Summary label="Time limit" value={examination.duration_minutes ? `${examination.duration_minutes} minutes` : 'Not set'} /><Summary label="Attempts" value={String(examination.attempt_limit)} /><Summary label="Passing" value={examination.passing_score ? `${examination.passing_score}%` : 'Not set'} /></div><section className="mt-6 rounded-xl border border-line bg-surface p-5" aria-labelledby="live-monitoring"><div className="flex flex-wrap items-baseline justify-between gap-2"><div><h2 id="live-monitoring" className="text-lg font-semibold">Live examination monitoring</h2><p className="mt-1 text-sm text-ink-muted">Refreshes every 15 seconds · last update {new Date(monitoring.refreshedAt).toLocaleTimeString()}</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-3 lg:grid-cols-6"><Summary label="Candidates" value={String(monitoring.totals.candidates)} /><Summary label="Active" value={String(monitoring.totals.active)} /><Summary label="Inactive" value={String(monitoring.totals.inactive)} /><Summary label="Submitted" value={String(monitoring.totals.submitted)} /><Summary label="Not started" value={String(monitoring.totals.notStarted)} /><Summary label="Expired" value={String(monitoring.totals.expired)} /></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[42rem] text-left text-sm"><caption className="sr-only">Candidate examination statuses</caption><thead className="border-b border-line"><tr><th className="p-3">Candidate</th><th className="p-3">Status</th><th className="p-3">Progress</th><th className="p-3">Last activity</th></tr></thead><tbody>{monitoring.candidates.map((row) => <tr key={row.candidate.id} className="border-b border-line last:border-0"><td className="p-3"><p className="font-medium">{row.candidate.name}</p><p className="text-ink-muted">{row.candidate.number}</p></td><td className="p-3 capitalize">{row.status.replace('_', ' ')}</td><td className="p-3">{row.answered} / {row.questionCount}</td><td className="p-3">{row.lastActivityAt ? new Date(row.lastActivityAt).toLocaleTimeString() : '—'}</td></tr>)}</tbody></table></div></section><section className="mt-6 rounded-xl border border-line bg-surface p-5"><h2 className="text-lg font-semibold">Candidate results</h2><p className="mt-1 text-sm text-ink-muted">{examination.release_results ? 'Released results are visible after submission.' : 'Results remain private until you release them.'}</p></section></>;
}

function Summary({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-line bg-surface p-4"><p className="text-sm text-ink-muted">{label}</p><p className="mt-1 font-semibold capitalize">{value}</p></div>; }
